---
apiVersion: v1
name: prometheus-libvirt-exporter
version: 1.0.0
appVersion: v0.1.1

nodeSelector: 
    openstack-compute-node: enabled

service:
    type: ClusterIP
    port: 9100
    targetPort: 9100
    nodePort:
    listenOnAllInterfaces: true
    annotations:
        prometheus.io/scrape: "true"