---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "libvirt-exporter.fullname" . }}
  labels:
{{- include "libvirt-exporter.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{- include "libvirt-exporter.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        exporter: libvirt
{{- include "libvirt-exporter.labels" . | indent 8 }}
    spec:
      containers:
      - name: libvirt-exporter
        securityContext:
          runAsUser: 0
          privileged: true
          readOnlyRootFilesystem: false
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: libvirt-sock
            mountPath: /var/run/libvirt/libvirt-sock
        ports:
        - name: metrics
          containerPort: 9177     
      volumes:
      - name: libvirt-sock
        hostPath:
          path: /var/run/libvirt/libvirt-sock
          type: Socket
{{- if .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.nodeSelector | indent 6 }}
{{- end }}

